<?php include 'database.php'; ?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yale: School of Art</title>
    <link rel="stylesheet" type="text/css" href="styles.css">
    <script>
        function scrollToSection(sectionId) {
            document.getElementById(sectionId).scrollIntoView({ behavior: 'smooth' });
        }
    </script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Acme&family=Source+Sans+3:ital,wght@0,200..900;1,200..900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <div class="university-name">
            <h1 style="margin-bottom: 0;">Yale University</h1>
            <h3 style="margin-top: 0;">School of Arts</h3>
        </div>
        <nav class="navigation-links">
            <a href="index.php">Home</a>
            <a href="aboutus.php">About us</a>
            <a href="apply.php">Apply Now</a>
            <a href="#">Exhibitions</a>
            <a href="#">Publications</a>
            <a href="#">News</a>
            <a href="login.php">Admin</a>
        </nav>
    </header>
    <h1 class="university" style="margin-top: 20px;">About Us</h1>

        <div class="about-us-container">
            <div>
                <h2 style="text-align:center">HISTORY</h2>
                <p>THE YALE SCHOOL OF ART IS A GRADUATE SCHOOL THAT CONFERS MASTER OF FINE ARTS DEGREES IN GRAPHIC DESIGN, PAINTING/PRINTMAKING, PHOTOGRAPHY, AND SCULPTURE
                Artists and designers of unusual promise and strong motivation are provided an educational context in which they can explore the potential of their own talents in the midst of an intense critical dialogue. 
                <br><br>This dialogue is generated by their peers, by distinguished visitors, and by a faculty comprised of professional artists of acknowledged accomplishment.
                The graduate student’s primary educational experience at Yale is centered on the student’s own studio activity. 
                <br><br>Supporting this enterprise are the experience, knowledge, and skills gained from rigorous, structured courses such as drawing, filmmaking, the relativity of color, and the rich academic offerings found throughout Yale. Each student is routinely exposed to many aesthetic positions through encounters with faculty members and visitors. The School is devoted not only to the refinement of visual skills, but also to the cultivation of the mind. Students must bring creative force and imagination to their own development, for these qualities cannot be taught—they can only be stimulated and appreciated.
                The School of Art offers an undergraduate art major for students in Yale College (see the bulletin Yale College Programs of Study). In addition, the School’s courses are open to students in the Graduate School of Arts and Sciences and other professional schools of the University, and School of Art students may enroll in elective courses in the Graduate School and other professional schools as well as in the College with permission.</p>
            </div>

            <div>
                <h2 style="text-align:center">MASTER OF FINE ARTS DEGREE (MFAS)</h2>
                <p>The degree of Master of Fine Arts is the only degree offered by the School of Art. It is conferred by the University upon recommendation of the faculty after successful completion of all course work in residence and after a thesis presentation that has been approved by the faculty. It implies distinctive achievement on the part of students in studies in the professional area of their choice and demonstrated capacity for independent work. The minimum residence requirement is two years. All candidates’ work is reviewed by faculty at the end of each term. If the work is not considered satisfactory, the student may not be invited back to complete the program (see section on Review and Awards under Academic Regulations in the chapter General Information). All degree candidates are expected to be present at the Commencement exercises in May unless excused by the dean.
                <br><br>Course work for the Master of Fine Arts degree carries a minimum of sixty credits. The disposition of these credits varies according to the area of study and is agreed upon at the time of registration between the student and the student’s faculty adviser.</p>
            </div>
        </div>

    <footer>
        <div class="footer-container">
            <div class="footer-content">
                <h1>Yale University</h1>
                <a>Visiting</a><br/>
                <a>Facebook</a><br/>
                <a>Instagram</a><br/>
                <a>Youtube</a><br/>
                <a>Sitemap</a><br/>
                <a>Accessibility at Yale</a><br/>
                <p>© 2024 Support the School</p>
            </div>
        </div>
    </footer>
</body>
</html>